language: java
jdk: oraclejdk8

services:
  - postgresql

before_script:
   - psql -c 'create database contacts' -U postgres

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - master

notifications:
email: false